language: python
python:
  - "2.7"
  - "3.5"
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirement.txt
branches:
  only:
   - master
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - sridharsha598@@gmail.com
    on_success: always
    on_failure: always
