language: python
python:
  - "3.8"
install:
  - pip install -r requirement.txt
script:
  - echo "skipping tests"
branches:
  only:
   - master
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - contact.klareda@gmail.com
    on_success: always
    on_failure: always
