jobs:
  build:
    docker:
      - image: cimg/python:3.9.4
    steps:
      - checkout
      - run: python3.9 -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python --version